### Read Customer data

In [1]:
import pandas as pd

In [2]:
df_customers = pd.read_json('data-engineering.csv')

In [3]:
df_customers

,id,name,ssn,birthday,gender,city,zip_code
0,20427847,Μάριος Γαρουφαλής,172-10-3586,1978-05-09,F,Γρεβενά,ΤΚ 763 78
1,74075652,Μόσχα Διαμαντοπούλου,140-57-5668,1994-03-05,F,Κομοτηνή,75665
2,31170608,Κλυταιμνήστρα Πέτση,548-79-9954,1971-08-24,M,Φλώρινα,ΤΚ 49056
3,39640871,Ευγενία Στρατογιάννη,036-43-6966,1988-12-19,M,Φλώρινα,65934
4,60718455,Χαρίτος-Τίμων Τσατσάνης,467-48-0823,1989-07-21,F,Θεσσαλονίκη,ΤΚ 38335
...,...,...,...,...,...,...,...
9995,58987369,Φανούριος Φραντζής,829-79-3954,1988-01-05,F,Αλεξανδρούπολη,41504
9996,91969721,Ισίδωρος Καραμάνος,594-48-3869,1977-09-15,M,Άμφισσα,ΤΚ 102 77
9997,97952284,Θεοφύλακτη Συμεωνίδου,189-71-2768,1987-01-08,F,Καβάλα,33414
9998,47054466,Ιππολύτη Τόλη,312-67-8638,1995-11-26,M,Βέροια,70697
9999,48277231,Βασίλειος Μαρκόπουλος,354-82-3047,1983-09-18,M,Κέρκυρα,09349

In [4]:
df_customers['id'].is_unique

False

In [5]:
# Find id which is duplicated

df_customers_duplicated = df_customers[df_customers['id'].duplicated() == True]
df_customers_duplicated

,id,name,ssn,birthday,gender,city,zip_code
6852,81570228,Ιππόλυτος Παπαδημητριάδης,428-19-7759,1978-10-05,M,Ξάνθη,573 32

In [6]:
# Two people with same id found (different names, birthdays etc.)
# In loan dataframe (later) delete loans associated to this bugged id

df_duplicated_id = df_customers[df_customers['id'] == 81570228]
df_duplicated_id

,id,name,ssn,birthday,gender,city,zip_code
5792,81570228,Μηνάς Σαμανίδης,016-05-9161,1985-12-17,M,Πρέβεζα,568 75
6852,81570228,Ιππόλυτος Παπαδημητριάδης,428-19-7759,1978-10-05,M,Ξάνθη,573 32

In [7]:
df_customers_zip_code_type = df_customers['zip_code'].map(type)
zip_code_types = df_customers_zip_code_type.unique()
print(zip_code_types)

[<class 'str'>]

In [8]:
df_customers['zip_code'] = df_customers['zip_code'].astype(str)

In [9]:
df_customers['zip_code'].replace(' ', '', regex=True, inplace=True)
df_customers['zip_code'] = df_customers.zip_code.str.extract('(\d+)')
df_customers['zip_code'] = df_customers['zip_code'].astype(int)

In [10]:
df_customers

,id,name,ssn,birthday,gender,city,zip_code
0,20427847,Μάριος Γαρουφαλής,172-10-3586,1978-05-09,F,Γρεβενά,76378
1,74075652,Μόσχα Διαμαντοπούλου,140-57-5668,1994-03-05,F,Κομοτηνή,75665
2,31170608,Κλυταιμνήστρα Πέτση,548-79-9954,1971-08-24,M,Φλώρινα,49056
3,39640871,Ευγενία Στρατογιάννη,036-43-6966,1988-12-19,M,Φλώρινα,65934
4,60718455,Χαρίτος-Τίμων Τσατσάνης,467-48-0823,1989-07-21,F,Θεσσαλονίκη,38335
...,...,...,...,...,...,...,...
9995,58987369,Φανούριος Φραντζής,829-79-3954,1988-01-05,F,Αλεξανδρούπολη,41504
9996,91969721,Ισίδωρος Καραμάνος,594-48-3869,1977-09-15,M,Άμφισσα,10277
9997,97952284,Θεοφύλακτη Συμεωνίδου,189-71-2768,1987-01-08,F,Καβάλα,33414
9998,47054466,Ιππολύτη Τόλη,312-67-8638,1995-11-26,M,Βέροια,70697
9999,48277231,Βασίλειος Μαρκόπουλος,354-82-3047,1983-09-18,M,Κέρκυρα,9349

### Read visits data

In [11]:
df_visits = pd.read_csv('http://rocker-data-engineering-task.storage.googleapis.com/data/visits.csv')
df_visits.rename(columns={"id" : "webvisit_id"}, inplace = True)
df_visits

       Unnamed: 0  webvisit_id   timestamp  referrer campaign_name
0               0     80139861  1533681013   Twitter      display1
1               1     80139861  1510371179  Facebook      display1
2               2     32212575  1523416988    Google      display2
3               3     32212575  1512331218  Facebook      display3
4               4     32212575  1537734220    Google      display2
...           ...          ...         ...       ...           ...
11179       11179     92350124  1522428982    Google      display3
11180       11180     92350124  1556022184  Facebook      display2
11181       11181     92350124  1548607154   Twitter      display2
11182       11182     31045174  1512875972   Twitter      display1
11183       11183     31045174  1509991924  Facebook      display3

[11184 rows x 5 columns]

In [12]:
df_visits['timestamp'] = pd.to_datetime(df_visits['timestamp'], unit='s')

In [13]:
import datetime as dt

df_visits['timestamp'] = pd.to_datetime(df_visits['timestamp'])

In [14]:
df_visits

       Unnamed: 0  webvisit_id           timestamp  referrer campaign_name
0               0     80139861 2018-08-07 22:30:13   Twitter      display1
1               1     80139861 2017-11-11 03:32:59  Facebook      display1
2               2     32212575 2018-04-11 03:23:08    Google      display2
3               3     32212575 2017-12-03 20:00:18  Facebook      display3
4               4     32212575 2018-09-23 20:23:40    Google      display2
...           ...          ...                 ...       ...           ...
11179       11179     92350124 2018-03-30 16:56:22    Google      display3
11180       11180     92350124 2019-04-23 12:23:04  Facebook      display2
11181       11181     92350124 2019-01-27 16:39:14   Twitter      display2
11182       11182     31045174 2017-12-10 03:19:32   Twitter      display1
11183       11183     31045174 2017-11-06 18:12:04  Facebook      display3

[11184 rows x 5 columns]

### Read loanfiles and merge them

In [15]:
loan_urls = [
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2017-10.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2017-11.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2017-12.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-1.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-10.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-11.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-12.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-2.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-3.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-4.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-5.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-6.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-7.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-8.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2018-9.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-1.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-10.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-2.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-3.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-4.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-5.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-6.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-7.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-8.csv",
    "http://rocker-data-engineering-task.storage.googleapis.com/data/loan-2019-9.csv"]

In [16]:
import numpy as np

loans = []
for url in loan_urls:
    df = pd.read_csv(url, index_col=None, header=0)
    loans.append(df)

merged_loans = pd.concat(loans, axis=0, ignore_index=True)

In [17]:
merged_loans.head(10)

,Unnamed: 0,id,user_id,timestamp,loan_amount,loan_purpose,outcome,interest,webvisit_id
0,12,9546870,33593540,1509162149,80000,Buying a pet,ACCEPTED,8.7,NaN
1,28,36469880,41352735,1508888134,270000,Refinance existing loans,REJECTED,6.7,"(72572646,)"
2,99,22554526,70055796,1507064389,240000,Home purchase,ACCEPTED,7.0,"(54404642,)"
3,117,27906548,17577009,1508660627,190000,Buying a pet,REJECTED,14.0,NaN
4,121,46601919,15988868,1508586823,20000,Home purchase,REJECTED,14.0,NaN
5,186,41957289,46805538,1508273362,300000,Refinance existing loans,REJECTED,7.0,NaN
6,206,99355109,76460475,1508359972,260000,Refinance existing loans,REJECTED,8.7,NaN
7,211,644608,29541965,1509054465,20000,Home purchase,REJECTED,7.0,"(72004328,)"
8,213,36909730,85885340,1507181154,190000,Refinance existing loans,REJECTED,14.0,NaN
9,222,74013266,78078336,1508715183,250000,Home purchase,ACCEPTED,7.0,NaN

In [18]:
merged_loans['timestamp'] = pd.to_datetime(merged_loans['timestamp'], unit='s')

In [19]:
merged_loans_duplicated = merged_loans[merged_loans['id'].duplicated() == True]
merged_loans_duplicated

Empty DataFrame
Columns: [Unnamed: 0, id, user_id, timestamp, loan_amount, loan_purpose, outcome, interest, webvisit_id]
Index: []

In [20]:
web_id = merged_loans[merged_loans['webvisit_id'].notna()]['webvisit_id']
for id in web_id:
    print(id)

(72572646,)
(54404642,)
(72004328,)
(65045146,)
(33871022,)
(13510410,)
(74932331,)
(74112627,)
(36329904,)
(69707929,)
(91841637,)
(13952841,)
(88106642,)
(89663670,)
(53462535,)
(94792045,)
(28821926,)
(68350579,)
(86926078,)
(97358485,)
(93427165,)
(68955779,)
(46286679,)
(81708413,)
(86041122,)
(78065381,)
(44793974,)
(65983710,)
(20094606,)
(12614998,)
(34494296,)
(38153546,)
(63313931,)
(85387475,)
(27714854,)
(70424406,)
(77709985,)
(3648752,)
(53577213,)
(2970548,)
(52777823,)
(30618519,)
(38017667,)
(64950959,)
(80415779,)
(10959272,)
(59554473,)
(65766927,)
(86874109,)
(6152719,)
(62862970,)
(78697538,)
(91086442,)
(74903554,)
(13385500,)
(81694097,)
(26882570,)
(48186089,)
(31922640,)
(71231623,)
(20525744,)
(22808048,)
(12160846,)
(58805743,)
(88880337,)
(88482131,)
(24649952,)
(58030575,)
(68151273,)
(64249825,)
(32249265,)
(22635104,)
(77734732,)
(18634941,)
(29104581,)
(24610846,)
(43533855,)
(55123097,)
(92457139,)
(89367508,)
(23412632,)
(68737710,)
(63160038,)
(42558738,)
(3039500,)
(55265437,)
(99337816,)
(33306453,)
(67290914,)
(11493715,)
(7064747,)
(16755704,)
(51980525,)
(56599014,)
(62811655,)
(57537567,)
(12674682,)
(28572966,)
(58766303,)
(5014923,)
(60850011,)
(84911144,)
(873685,)
(3709274,)
(96837271,)
(42604891,)
(80157388,)
(40597895,)
(56159495,)
(32958350,)
(33250923,)
(64615951,)
(32592235,)
(62720921,)
(95759021,)
(38819440,)
(65414261,)
(90293649,)
(49716225,)
(38186449,)
(61266603,)
(54773275,)
(42633225,)
(4950539,)
(57912319,)
(45687952,)
(33638529,)
(68210025,)
(93292479,)
(60442276,)
(35150095,)
(38840610,)
(42778448,)
(61381031,)
(52967565,)
(93785793,)
(50578341,)
(84353476,)
(54747726,)
(37871921,)
(75392425,)
(42245264,)
(45247779,)
(27237948,)
(87003668,)
(910992,)
(11069105,)
(27303880,)
(33691982,)
(22990247,)
(46082902,)
(1529548,)
(17548700,)
(31455593,)
(90479276,)
(88250801,)
(11133553,)
(1490927,)
(63330784,)
(10009718,)
(6763258,)
(60689361,)
(89668248,)
(59743150,)
(50776084,)
(43175944,)
(8989422,)
(32212575,)
(50229931,)
(96342007,)
(61658137,)
(14630962,)
(50001699,)
(54921437,)
(25991791,)
(3408072,)
(64393070,)
(26013143,)
(94395910,)
(41872459,)
(89076002,)
(33887291,)
(13787169,)
(92783658,)
(31317854,)
(45040121,)
(36148845,)
(99411410,)
(65375973,)
(14067363,)
(29004674,)
(23585411,)
(91820387,)
(93121621,)
(58754889,)
(59647914,)
(14751287,)
(88641319,)
(3968492,)
(52208700,)
(45155314,)
(85249067,)
(62669120,)
(69703504,)
(97354843,)
(32483961,)
(50022268,)
(91754020,)
(40006859,)
(47631696,)
(29489867,)
(28025154,)
(33513218,)
(11245254,)
(65721853,)
(68519186,)
(95482494,)
(71859539,)
(56019728,)
(12498534,)
(56249059,)
(31192059,)
(76106804,)
(84445560,)
(26804566,)
(28955050,)
(62818787,)
(25389604,)
(79780098,)
(80141777,)
(17709071,)
(24799619,)
(59197837,)
(755308,)
(8480245,)
(39663977,)
(67490618,)
(98213123,)
(57357182,)
(21770972,)
(2165316,)
(76528430,)
(81519631,)
(47934487,)
(85706526,)
(4672625,)
(72279537,)
(37186451,)
(32095722,)
(33044664,)
(83940383,)
(18073193,)
(80165960,)
(72968285,)
(22151091,)
(18860340,)
(26615506,)
(8925806,)
(54338195,)
(8548441,)
(21316056,)
(71111751,)
(53744502,)
(88365816,)
(92920294,)
(96199295,)
(30837373,)
(65070239,)
(27614219,)
(91936188,)
(23563866,)
(75973270,)
(63352063,)
(26911839,)
(66314215,)
(82050525,)
(75053360,)
(89018919,)
(4413573,)
(2914073,)
(86629841,)
(33224654,)
(17722538,)
(16698668,)
(10367174,)
(54536694,)
(88954,)
(30016281,)
(92543909,)
(75341839,)
(72278124,)
(13901298,)
(749206,)
(8336088,)
(36810640,)
(24863930,)
(94562313,)
(73345413,)
(4262508,)
(9400008,)
(23399038,)
(40687976,)
(54042222,)
(67653316,)
(46650470,)
(78069096,)
(21751962,)
(37417031,)
(95327465,)
(38834928,)
(14783729,)
(10022842,)
(2209937,)
(93983148,)
(78226838,)
(61228287,)
(39018835,)
(48348313,)
(37256418,)
(2510951,)
(21048654,)
(59465201,)
(33622602,)
(11030221,)
(90557393,)
(10706125,)
(39689331,)
(78101342,)
(91546110,)
(55746280,)
(15767846,)
(18825880,)
(34405575,)
(24122535,)
(54354971,)
(89151535,)
(98129983,)
(74076929,)
(70611160,)
(70316856,)
(46915498,)
(28480646,)
(19475055,)
(8272632,)
(78706202,)
(80825564,)
(66108557,)
(21968143,)
(49727397,)
(66864278,)
(57310417,)
(38342006,)
(70960075,)
(71714668,)
(36358225,)
(73744246,)
(81930068,)
(71856987,)
(83740406,)
(26814135,)
(71091866,)
(74930442,)
(38438555,)
(1626345,)
(78024307,)
(61928137,)
(86741762,)
(64433750,)
(59550562,)
(74470625,)
(50712061,)
(68296913,)
(78995950,)
(60327042,)
(66618353,)
(71429861,)
(2094623,)
(26931693,)
(74368390,)
(60922642,)
(703191,)
(37413067,)
(14017209,)
(50555284,)
(5698930,)
(65365412,)
(71095754,)
(72860820,)
(64954708,)
(83457822,)
(14262618,)
(72360118,)
(27773056,)
(58287186,)
(76129675,)
(63361476,)
(80857879,)
(48340204,)
(9914430,)
(18967422,)
(52434361,)
(63352603,)
(68188106,)
(68610541,)
(84798732,)
(41560206,)
(83545553,)
(88405866,)
(67151626,)
(73366063,)
(20560449,)
(80337573,)
(72683192,)
(61558416,)
(45149893,)
(84589576,)
(19433674,)
(23927601,)
(46830064,)
(13438727,)
(41458584,)
(79334651,)
(41983759,)
(47653856,)
(34537813,)
(77322686,)
(8349942,)
(71278126,)
(97753230,)
(67989414,)
(16753332,)
(25737084,)
(14953216,)
(11599327,)
(34802335,)
(17815598,)
(45460703,)
(7241414,)
(6133715,)
(4478513,)
(46092592,)
(8811549,)
(26193777,)
(59482276,)
(82883328,)
(30684533,)
(30052492,)
(16938833,)
(85752686,)
(5347955,)
(59802565,)
(24535109,)
(52645861,)
(67467045,)
(84642093,)
(88304918,)
(42928531,)
(36419319,)
(68858296,)
(76196232,)
(31238237,)
(403229,)
(43686785,)
(9569113,)
(16593344,)
(84898018,)
(42601887,)
(23331694,)
(84813705,)
(58134287,)
(46771898,)
(87685271,)
(76882526,)
(78720158,)
(65093205,)
(41432078,)
(5260890,)
(65239323,)
(93759694,)
(62961920,)
(89255100,)
(39383050,)
(84939587,)
(25308400,)
(8582447,)
(20137705,)
(64233259,)
(2531619,)
(70651400,)
(49473508,)
(92001714,)
(55377156,)
(94230553,)
(31457834,)
(48197609,)
(15420726,)
(77220646,)
(61161977,)
(97192775,)
(35017871,)
(59734128,)
(56333594,)
(51484231,)
(56528660,)
(94990604,)
(30173943,)
(95086624,)
(57912391,)
(92372689,)
(15823115,)
(48359424,)
(31295670,)
(50040344,)
(19030131,)
(4733370,)
(41081268,)
(87765330,)
(30656793,)
(67024987,)
(44920642,)
(66362874,)
(38323365,)
(79737665,)
(82178571,)
(73059568,)
(44829815,)
(74842400,)
(90966721,)
(93647618,)
(10174364,)
(7711761,)
(13213586,)
(7332698,)
(46608009,)
(8461362,)
(62393163,)
(47756460,)
(50954912,)
(79085421,)
(40318966,)
(95506896,)
(62842960,)
(47726204,)
(26855833,)
(4983298,)
(77467517,)
(762251,)
(9334197,)
(54735615,)
(16550838,)
(73883299,)
(56934340,)
(17230765,)
(60239916,)
(34464176,)
(25561724,)
(99103073,)
(88272477,)
(32071333,)
(10739772,)
(50513370,)
(35658917,)
(42613249,)
(5297309,)
(77800979,)
(60803999,)
(29405665,)
(32346539,)
(56820852,)
(83606540,)
(42000246,)
(40409195,)
(19681740,)
(56821711,)
(5345317,)
(23046077,)
(83572617,)
(86252202,)
(99655466,)
(47627240,)
(69574577,)
(40935526,)
(96112094,)
(64020813,)
(75732668,)
(51049134,)
(43387380,)
(77439488,)
(79893481,)
(62891970,)
(98091983,)
(89128754,)
(28446841,)
(35882538,)
(66271427,)
(59115508,)
(42110094,)
(61769288,)
(35858714,)
(80461880,)
(86768270,)
(3106047,)
(39263212,)
(18569521,)
(58437811,)
(10362390,)
(17631253,)
(60425249,)
(91603774,)
(93621234,)
(44656181,)
(70114920,)
(44242398,)
(35703658,)
(37961231,)
(82169534,)
(75380312,)
(73787242,)
(3678111,)
(66559727,)
(966667,)
(92414210,)
(16672347,)
(63163006,)
(48801073,)
(70591291,)
(55525450,)
(59209363,)
(80037834,)
(9894569,)
(75944382,)
(80949693,)
(4938450,)
(58611813,)
(77646886,)
(2091824,)
(33937354,)
(76293895,)
(16599258,)
(29579923,)
(73946053,)
(60265281,)
(65364439,)
(53060086,)
(25599800,)
(16785778,)
(22340361,)
(30745623,)
(32954050,)
(85794818,)
(82344447,)
(86809558,)
(31637163,)
(95713091,)
(74662667,)
(64423085,)
(38860234,)
(1568091,)
(72082707,)
(69350116,)
(34045703,)
(39858558,)
(81789695,)
(97239908,)
(87059036,)
(93396750,)
(10235190,)
(42604721,)
(82638890,)
(14393902,)
(81042817,)
(29823230,)
(34714125,)
(95013036,)
(87606107,)
(69457241,)
(33955424,)
(4144524,)
(85579833,)
(32113147,)
(56407255,)
(6048268,)
(78524961,)
(40103579,)
(79903044,)
(75382587,)
(81365520,)
(22302755,)
(65911583,)
(24530884,)
(78544118,)
(41718058,)
(42124052,)
(91806982,)
(99629698,)
(61489319,)
(65478956,)
(66872445,)
(11657600,)
(19448843,)
(63858967,)
(20485466,)
(46010675,)
(16849484,)
(21236731,)
(28156720,)
(16159895,)
(22760076,)
(57533430,)
(4202586,)
(67166826,)
(56560134,)
(19975852,)
(60781513,)
(88462451,)
(42136846,)
(85864632,)
(94497489,)
(8147280,)
(11232773,)
(92989098,)
(24734870,)
(43554321,)
(28990486,)
(10459484,)
(29917682,)
(97129168,)
(13180188,)
(18602716,)
(7344328,)
(21647474,)
(77567590,)
(58532378,)
(33225117,)
(46646045,)
(95820313,)
(74236981,)
(68502683,)
(48560285,)
(45386250,)
(60183352,)
(75632828,)
(96797831,)
(60189013,)
(36045122,)
(3276468,)
(65704259,)
(71361177,)
(41873878,)
(55140700,)
(19357531,)
(82278407,)
(18365252,)
(39871927,)
(9504190,)
(77242765,)
(10569194,)
(9082007,)
(6870988,)
(6890498,)
(63224336,)
(23117872,)
(27402367,)
(93467290,)
(75582459,)
(68540156,)
(12126337,)
(59446220,)
(31807130,)
(97035597,)
(7941585,)
(54477570,)
(59573253,)
(37317482,)
(40552595,)
(79103988,)
(68930376,)
(89892727,)
(41207174,)
(56124620,)
(80415152,)
(70549520,)
(51966982,)
(84930519,)
(86399806,)
(90013250,)
(43949682,)
(68015299,)
(83209920,)
(86653137,)
(76965969,)
(48360786,)
(45224532,)
(84276441,)
(12889079,)
(70549598,)
(74594161,)
(43509281,)
(83704200,)
(27878693,)
(25785197,)
(64032105,)
(48178401,)
(58295413,)
(58547138,)
(9553407,)
(70850216,)
(10035493,)
(31888874,)
(5146717,)
(52902584,)
(79754323,)
(75131880,)
(11422830,)
(95388950,)
(82388967,)
(19339382,)
(81478487,)
(72842159,)
(68555559,)
(25188305,)
(31461549,)
(33501077,)
(59003084,)
(83697243,)
(36031670,)
(30656306,)
(26307259,)
(71515566,)
(42576877,)
(17644637,)
(36305327,)
(61140462,)
(15729428,)
(78673882,)
(29443853,)
(4884317,)
(98957491,)
(50547446,)
(48178447,)
(19257514,)
(74105207,)
(99407174,)
(34363915,)
(14234077,)
(49611708,)
(86931503,)
(25588606,)
(67412323,)
(66438629,)
(82263859,)
(84357407,)
(85854038,)
(85495252,)
(72780950,)
(15479820,)
(88531233,)
(88040634,)
(88580715,)
(67697277,)
(22292220,)
(67798084,)
(68399196,)
(85929682,)
(67870227,)
(70360775,)
(65379582,)
(63570367,)
(69224711,)
(87582221,)
(76795495,)
(63137404,)
(42299307,)
(29306816,)
(38905042,)
(11736904,)
(35895187,)
(21749232,)
(7044150,)
(54732553,)
(89557408,)
(24585076,)
(88390631,)
(96983490,)
(2173563,)
(84767806,)
(88410956,)
(50125475,)
(85385385,)
(76854088,)
(97260136,)
(22685677,)
(51313844,)
(46893225,)
(5599211,)
(91689405,)
(47451601,)
(79606605,)
(368684,)
(22791978,)
(87218508,)
(87425787,)
(32453742,)
(36524699,)
(65724425,)
(29694500,)
(97610357,)
(15295241,)
(55930753,)
(31986029,)
(19128763,)
(38425658,)
(83519376,)
(47573595,)
(58547219,)
(79672056,)
(92842742,)
(85157438,)
(78301782,)
(21945540,)
(35408103,)
(72302744,)
(52228297,)
(65569848,)
(64219178,)
(31936250,)
(22352083,)
(6337995,)
(65806010,)
(79292446,)
(79076531,)
(78676531,)
(26019968,)
(28696444,)
(31783997,)
(35271603,)
(83558658,)
(44483348,)
(62262730,)
(96779582,)
(39167206,)
(24623856,)
(50678790,)
(94124294,)
(80719070,)
(25347467,)
(15512002,)
(42110813,)
(34121491,)
(49192249,)
(89970166,)
(25498152,)
(11921635,)
(22899861,)
(48957132,)
(13871914,)
(21860873,)
(77588360,)
(48608144,)
(79344861,)
(23653281,)
(61538921,)
(35521533,)
(13537355,)
(53119807,)
(44740634,)
(57494334,)
(47792204,)
(78717172,)
(94083403,)
(41449234,)
(25549053,)
(33522382,)
(24688294,)
(46299413,)
(73898131,)
(18267557,)
(64679421,)
(36451960,)
(75350862,)
(72219451,)
(96358451,)
(44618909,)
(90263935,)
(39036170,)
(85678623,)
(27864059,)
(15260168,)
(12073927,)
(87376303,)
(66305565,)
(5824614,)
(43069103,)
(37918173,)
(98147884,)
(80441425,)
(48772057,)
(76723457,)
(28652080,)
(38138899,)
(79850824,)
(22942764,)
(43027100,)
(65212925,)
(95803995,)
(91616256,)
(88740975,)
(42972567,)
(27530313,)
(65043381,)
(77931497,)
(85139938,)
(90626943,)
(19280558,)
(14546811,)
(32287827,)
(46949021,)
(3245327,)
(58114883,)
(86206013,)
(78096519,)
(57717392,)
(42391875,)
(40176255,)
(41540500,)
(88777168,)
(92309219,)
(40837526,)
(50297158,)
(17870989,)
(24757848,)
(836489,)
(66889062,)
(17891051,)
(85809217,)
(65780958,)
(78853623,)
(38676148,)
(3759107,)
(53331821,)
(81276045,)
(25296617,)
(71847261,)
(64576119,)
(73780043,)
(72731787,)
(24419372,)
(70945038,)
(26090874,)
(26415497,)
(66009813,)
(88914662,)
(13539124,)
(7729927,)
(49878196,)
(95993909,)
(53681692,)
(75962018,)
(25153921,)
(20205802,)
(51887331,)
(12856308,)
(34208612,)
(40120229,)
(1669939,)
(20233512,)
(20482011,)
(68704132,)
(66172369,)
(95326018,)
(54739388,)
(23002733,)
(48634429,)
(85348023,)
(9668112,)
(14677050,)
(36950703,)
(79623896,)
(33426728,)
(54379181,)
(7617037,)
(80482707,)
(62089649,)
(58869031,)
(97330154,)
(29160297,)
(49445575,)
(49592903,)
(99808091,)
(99688174,)
(13101834,)
(65395195,)
(36077198,)
(94143413,)
(92408825,)
(48173274,)
(54052264,)
(82000347,)
(9032795,)
(78048104,)
(30465776,)
(54436264,)
(88837149,)
(84843640,)
(61146204,)
(17326682,)
(60871057,)
(44997926,)
(40604065,)
(39081066,)
(3833218,)
(27598485,)
(62706863,)
(34087567,)
(446218,)
(44040626,)
(81198265,)
(27590602,)
(18657661,)
(9376000,)
(21816697,)
(79340987,)
(10661625,)
(17685275,)
(16599644,)
(24689845,)
(95699547,)
(71343116,)
(25073132,)
(79688567,)
(32183676,)
(2776752,)
(64196028,)
(53859979,)
(23714947,)
(19779542,)
(43917817,)
(60554754,)
(18327947,)
(65665875,)
(33067109,)
(76376527,)
(10402167,)
(71911345,)
(80186701,)
(95710812,)
(81429545,)
(40101095,)
(92764191,)
(77991108,)
(85736647,)
(10850014,)
(42082717,)
(23624843,)
(83669271,)
(39956764,)
(26318053,)
(27243165,)
(31645311,)
(34534014,)
(27349715,)
(29011730,)
(68249447,)
(24882987,)
(75750597,)
(3673141,)
(95261246,)
(92687220,)
(41197458,)
(81461917,)
(72691634,)
(20051362,)
(63623300,)
(87342436,)
(34318327,)
(61505779,)
(83477677,)
(92356424,)
(82538928,)
(62525133,)
(93934955,)
(81732623,)
(30882036,)
(31352993,)
(24549374,)
(28356588,)
(45761101,)
(18828128,)
(55117452,)
(40145236,)
(97347000,)
(66599297,)
(16944100,)
(85919133,)
(57435566,)
(17475512,)
(38312980,)
(67938795,)
(7202997,)
(63995244,)
(43553473,)
(89940479,)
(4288071,)
(25731031,)
(41013744,)
(88849972,)
(14112699,)
(92467080,)
(84059601,)
(38205678,)
(13447895,)
(35606499,)
(24516690,)
(99938251,)
(63406971,)
(33058745,)
(43619558,)
(93368679,)
(20953972,)
(17408252,)
(79405447,)
(93571493,)
(55309620,)
(81653709,)
(19030360,)
(50639238,)
(61529782,)
(77145474,)
(53081562,)
(79744030,)
(55778260,)
(53830690,)
(94878079,)
(13294815,)
(70542144,)
(40304160,)
(35905099,)
(58337485,)
(2516690,)
(13730233,)
(73532116,)
(93583653,)
(94794740,)
(23679538,)
(73582701,)
(49619487,)
(73831089,)
(27845923,)
(89303326,)
(65731175,)
(69916663,)
(65486892,)
(76064767,)
(6961284,)
(24335536,)
(55013770,)
(86588671,)
(89421389,)
(38972875,)
(21556366,)
(36161119,)
(72645630,)
(5457981,)
(47594318,)
(69665998,)
(80417025,)
(98383606,)
(4263972,)
(10442842,)
(20029998,)
(55331691,)
(14418369,)
(26879212,)
(68722977,)
(7258110,)
(82932457,)
(3938852,)
(23279358,)
(83138031,)
(19369789,)
(43970436,)
(16170346,)
(21551512,)
(868838,)
(75943642,)
(17582955,)
(86033376,)
(73157678,)
(98154068,)
(62300680,)
(52420332,)
(46627459,)
(18979985,)
(80017401,)
(62579193,)
(97945933,)
(78982190,)
(763525,)
(31809365,)
(10894767,)
(70789008,)
(31471445,)
(76372994,)
(60050416,)
(11123359,)
(1446631,)
(5923708,)
(63340682,)
(21452880,)
(62266853,)
(67939155,)
(71729487,)
(79721517,)
(4830592,)
(39144149,)
(49630725,)
(21257521,)
(86753186,)
(15336482,)
(38946193,)
(51544118,)
(9984416,)
(91927516,)
(49680781,)
(57164933,)
(34261764,)
(7434748,)
(41490672,)
(80825687,)
(87830797,)
(62897113,)
(37167087,)
(26133178,)
(88465529,)
(85884953,)
(35097509,)
(80271539,)
(3378292,)
(14955877,)
(36271540,)
(3703891,)
(49674480,)
(4191616,)
(26759416,)
(91308389,)
(41307083,)
(38773591,)
(85567579,)
(57917268,)
(40231373,)
(70022569,)
(10865180,)
(9522673,)
(61901406,)
(85809761,)
(58702655,)
(83652220,)
(87692910,)
(75863828,)
(82439042,)
(71087637,)
(98517250,)
(74929094,)
(56835174,)
(14675353,)
(16943383,)
(44157240,)
(34595050,)
(409582,)
(86111844,)
(58501371,)
(91842083,)
(73634469,)
(46637014,)
(28106127,)
(86202850,)
(79775335,)
(59192440,)
(82004869,)
(71951731,)
(17974455,)
(74545543,)
(83331777,)
(59978147,)
(9474053,)
(6911156,)
(71205288,)
(65743094,)
(82479600,)
(77689732,)
(99218585,)
(43884163,)
(83490256,)
(60194860,)
(67726429,)
(32468113,)
(68019884,)
(24699092,)
(41701852,)
(78153126,)
(71906839,)
(23988360,)
(133397,)
(2201012,)
(77604866,)
(88910570,)
(44230011,)
(77145404,)
(50714759,)
(79177120,)
(16430996,)
(51509357,)
(49179312,)
(60936474,)
(91105190,)
(50688929,)
(34932411,)
(46258693,)
(43623554,)
(44226294,)
(67661338,)
(12778895,)
(11511228,)
(35446016,)
(25960178,)
(7675446,)
(55147466,)
(53997833,)
(29614867,)
(8535330,)
(36106044,)
(85748715,)
(84723929,)
(75843375,)
(34011394,)
(81878841,)
(27988436,)
(2805407,)
(65482197,)
(92611122,)
(53673773,)
(70757175,)
(85004549,)
(25119372,)
(66331845,)
(78335170,)
(24620769,)
(83453879,)
(51554001,)
(87521502,)
(36380306,)
(168957,)
(52393787,)
(29075187,)
(41137672,)
(65461923,)
(67462960,)
(17061862,)
(69058961,)
(57951031,)
(13957974,)
(21356933,)
(48806420,)
(82026338,)
(29125436,)
(46132136,)
(90092018,)
(31714223,)
(26416596,)
(12574296,)
(50047145,)
(65675629,)
(76775109,)
(31040936,)
(39868330,)
(76067851,)
(55153990,)
(50236267,)
(75806948,)
(27330639,)
(29445694,)
(16101503,)
(91830967,)
(93321828,)
(30043278,)
(24391299,)
(37082703,)
(27599124,)
(13438803,)
(50378696,)
(73847268,)
(79763174,)
(37522498,)
(32553576,)
(8687708,)
(38108183,)
(37266797,)
(96692211,)
(1132281,)
(36997216,)
(45415154,)
(62233727,)
(92651209,)
(42274859,)
(12809926,)
(66422935,)
(67462601,)
(29399181,)
(90492162,)
(80514067,)
(37582052,)
(13697359,)
(66238430,)
(20415299,)
(60945878,)
(84078205,)
(19696909,)
(54840793,)
(51936081,)
(51764879,)
(4177656,)
(66830566,)
(82368247,)
(41151751,)
(62713353,)
(3589855,)
(12908583,)
(19786435,)
(78545367,)
(86653760,)
(83777956,)
(97767748,)
(10889031,)
(96749664,)
(40015937,)
(27892848,)
(807841,)
(85944874,)
(83809,)
(84009225,)
(45597995,)
(8865220,)
(43232205,)
(78849936,)
(52785109,)
(50998149,)
(29915332,)
(31436475,)
(25575001,)
(39771408,)
(369269,)
(49068214,)
(84539318,)
(13681456,)
(54761715,)
(49985087,)
(15186056,)
(68318698,)
(49155124,)
(95465475,)
(13439683,)
(21705934,)
(49853559,)
(16632881,)
(89799276,)
(41421871,)
(96754164,)
(3489092,)
(86927300,)
(74570676,)
(31794032,)
(93233925,)
(39987833,)
(94973954,)
(53072843,)
(82049041,)
(21658711,)
(78330106,)
(48636340,)
(81763674,)
(17216301,)
(41588429,)
(60118473,)
(57239474,)
(40613848,)
(56464852,)
(87310527,)
(94418175,)
(62456985,)
(37397000,)
(41471168,)
(97345080,)
(59212858,)
(5840564,)
(92446554,)
(13278436,)
(97079601,)
(82207748,)
(54182230,)
(94375965,)
(56600436,)
(87838691,)
(48810143,)
(68923321,)
(5321290,)
(12223224,)
(79889969,)
(87042434,)
(83595060,)
(76118248,)
(77282310,)
(25134792,)
(63279702,)
(74515016,)
(12093854,)
(93081289,)
(36850016,)
(92742268,)
(79853195,)
(23416755,)
(61943998,)
(10280580,)
(7220306,)
(57243795,)
(5950042,)
(72979832,)
(95674870,)
(68819619,)
(46440286,)
(43448433,)
(19270360,)
(96376179,)
(62879744,)
(55572778,)
(72936642,)
(28533225,)
(35616067,)
(83032292,)
(50751920,)
(64938643,)
(15563145,)
(32927716,)
(49853520,)
(6814417,)
(43488671,)
(45535047,)
(77630543,)
(49342645,)
(5866874,)
(87540385,)
(59753653,)
(57300167,)
(14034615,)
(96913303,)
(75806253,)
(81200509,)
(65193575,)
(1385366,)
(96097028,)
(62534137,)
(95434714,)
(14939999,)
(85148091,)
(98681569,)
(18931501,)
(94609342,)
(67096963,)
(28033556,)
(21324469,)
(43783881,)
(79587498,)
(16373155,)
(73012129,)
(61763807,)
(92002949,)
(64367836,)
(77412384,)
(61898537,)
(5016320,)
(9470029,)

In [21]:
merged_loans['webvisit_id'].replace(',', '', regex=True, inplace=True)
merged_loans['webvisit_id'] = merged_loans['webvisit_id'].str.strip('()')
merged_loans['webvisit_id'] = merged_loans['webvisit_id'].replace(np.nan, 0)

In [22]:
merged_loans['id'].is_unique

True

In [23]:
loan_purpose_values = merged_loans['loan_purpose'].unique()
print(loan_purpose_values)

['Buying a pet' 'Refinance existing loans' 'Home purchase' 'home purchase'
 'buying a pet']

In [24]:
merged_loans['loan_purpose'].replace({"buying a pet": "Buying a pet", "home purchase": "Home purchase"}, inplace=True)

In [25]:
loan_purpose_values = merged_loans['loan_purpose'].unique()
print(loan_purpose_values)

['Buying a pet' 'Refinance existing loans' 'Home purchase']

In [26]:
outcome_values = merged_loans['outcome'].unique()
print(outcome_values)

['ACCEPTED' 'REJECTED']

In [27]:
interest_values = merged_loans['interest'].unique()
print(sorted(interest_values))

[6.7, 7.0, 8.7, 14.0]

#### Prepare webvisit data to be merged into loans

In [28]:
df_webvisit_id_type = merged_loans['webvisit_id'].map(type)
webvisit_types = df_webvisit_id_type.unique()
print(webvisit_types)

[<class 'int'> <class 'str'>]

In [29]:
df_visits_id_type = df_visits['webvisit_id'].map(type)
visits_types = df_visits_id_type.unique()
print(visits_types)

[<class 'int'>]

In [30]:
merged_loans['webvisit_id'] = merged_loans['webvisit_id'].astype(int)

In [31]:
df_visits['webvisit_id'].is_unique

False

In [32]:
df_visits.dtypes

Unnamed: 0                int64
webvisit_id               int64
timestamp        datetime64[ns]
referrer                 object
campaign_name            object
dtype: object

In [33]:
df_visits = df_visits.astype(str)

##### Merge data for rows in webvisit dataframe that share the same webvisit_id

In [34]:
df_visits['timestamp'] = df_visits.groupby(['webvisit_id'])['timestamp'].transform(lambda x : ','.join(x))

In [35]:
df_visits['referrer'] = df_visits.groupby(['webvisit_id'])['referrer'].transform(lambda x : ','.join(x))

In [36]:
df_visits['campaign_name'] = df_visits.groupby(['webvisit_id'])['campaign_name'].transform(lambda x : ','.join(x))

In [37]:
df_visits.drop_duplicates(subset=['webvisit_id', 'timestamp', 'referrer', 'campaign_name'], keep='first', inplace=True)

In [38]:
df_visits['webvisit_id'] = df_visits['webvisit_id'].astype(int)

In [39]:
merged_loans = merged_loans.merge(df_visits, on='webvisit_id', how='left')
merged_loans.head(100)

,Unnamed: 0_x,id,user_id,timestamp_x,loan_amount,loan_purpose,outcome,interest,webvisit_id,Unnamed: 0_y,timestamp_y,referrer,campaign_name
0,12,9546870,33593540,2017-10-28 03:42:29,80000,Buying a pet,ACCEPTED,8.7,0,NaN,NaN,NaN,NaN
1,28,36469880,41352735,2017-10-24 23:35:34,270000,Refinance existing loans,REJECTED,6.7,72572646,27,2018-09-20 16:49:33,Google,display2
2,99,22554526,70055796,2017-10-03 20:59:49,240000,Home purchase,ACCEPTED,7.0,54404642,65,2018-09-23 09:55:30,Twitter,display3
3,117,27906548,17577009,2017-10-22 08:23:47,190000,Buying a pet,REJECTED,14.0,0,NaN,NaN,NaN,NaN
4,121,46601919,15988868,2017-10-21 11:53:43,20000,Home purchase,REJECTED,14.0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2139,41303075,41215957,2017-10-07 21:42:02,50000,Buying a pet,ACCEPTED,6.7,0,NaN,NaN,NaN,NaN
96,2174,64760392,51453919,2017-10-21 04:25:59,280000,Buying a pet,ACCEPTED,6.7,0,NaN,NaN,NaN,NaN
97,2190,95726669,47248599,2017-10-30 14:02:05,280000,Refinance existing loans,ACCEPTED,8.7,0,NaN,NaN,NaN,NaN
98,2277,74922937,5863725,2017-10-26 14:31:48,230000,Refinance existing loans,ACCEPTED,7.0,0,NaN,NaN,NaN,NaN
99,2281,95836622,48747986,2017-10-30 14:14:15,270000,Refinance existing loans,REJECTED,8.7,0,NaN,NaN,NaN,NaN

In [40]:
merged_loans['id'].is_unique

True

In [41]:
# Loans associated to bugged user_id
merged_loans[merged_loans['user_id'] == 81570228]

,Unnamed: 0_x,id,user_id,timestamp_x,loan_amount,loan_purpose,outcome,interest,webvisit_id,Unnamed: 0_y,timestamp_y,referrer,campaign_name
7579,8729,52607839,81570228,2018-07-02 12:44:22,220000,Buying a pet,ACCEPTED,14.0,25919562,6488,2019-03-21 15:41:21,Facebook,display1
7658,10312,12867945,81570228,2018-07-04 03:39:23,40000,Refinance existing loans,ACCEPTED,8.7,0,NaN,NaN,NaN,NaN
8292,10311,39476417,81570228,2018-08-03 19:28:23,170000,Home purchase,ACCEPTED,6.7,0,NaN,NaN,NaN,NaN

In [42]:
df_customers.rename(columns={"id": "user_id"}, inplace=True)
df_customers

,user_id,name,ssn,birthday,gender,city,zip_code
0,20427847,Μάριος Γαρουφαλής,172-10-3586,1978-05-09,F,Γρεβενά,76378
1,74075652,Μόσχα Διαμαντοπούλου,140-57-5668,1994-03-05,F,Κομοτηνή,75665
2,31170608,Κλυταιμνήστρα Πέτση,548-79-9954,1971-08-24,M,Φλώρινα,49056
3,39640871,Ευγενία Στρατογιάννη,036-43-6966,1988-12-19,M,Φλώρινα,65934
4,60718455,Χαρίτος-Τίμων Τσατσάνης,467-48-0823,1989-07-21,F,Θεσσαλονίκη,38335
...,...,...,...,...,...,...,...
9995,58987369,Φανούριος Φραντζής,829-79-3954,1988-01-05,F,Αλεξανδρούπολη,41504
9996,91969721,Ισίδωρος Καραμάνος,594-48-3869,1977-09-15,M,Άμφισσα,10277
9997,97952284,Θεοφύλακτη Συμεωνίδου,189-71-2768,1987-01-08,F,Καβάλα,33414
9998,47054466,Ιππολύτη Τόλη,312-67-8638,1995-11-26,M,Βέροια,70697
9999,48277231,Βασίλειος Μαρκόπουλος,354-82-3047,1983-09-18,M,Κέρκυρα,9349

In [43]:
merged_loans = merged_loans.merge(df_customers, on='user_id', how='left')
merged_loans.head(100)

,Unnamed: 0_x,id,user_id,timestamp_x,loan_amount,loan_purpose,outcome,interest,webvisit_id,Unnamed: 0_y,timestamp_y,referrer,campaign_name,name,ssn,birthday,gender,city,zip_code
0,12,9546870,33593540,2017-10-28 03:42:29,80000,Buying a pet,ACCEPTED,8.7,0,NaN,NaN,NaN,NaN,Δράκων-Δαμιανός Μητρίδης,826-19-7609,1983-05-06,M,Λαμία,37988
1,28,36469880,41352735,2017-10-24 23:35:34,270000,Refinance existing loans,REJECTED,6.7,72572646,27,2018-09-20 16:49:33,Google,display2,Κομνηνή Βρακά,388-36-2125,1984-10-13,F,Σπάρτη,44532
2,99,22554526,70055796,2017-10-03 20:59:49,240000,Home purchase,ACCEPTED,7.0,54404642,65,2018-09-23 09:55:30,Twitter,display3,Ελπίς-Λυδία Παυλίδου,506-77-6759,1984-07-14,F,Λιβαδιά,71745
3,117,27906548,17577009,2017-10-22 08:23:47,190000,Buying a pet,REJECTED,14.0,0,NaN,NaN,NaN,NaN,Αλκμήνη Ματεντσίδου,053-49-2562,1973-02-25,F,Καβάλα,87994
4,121,46601919,15988868,2017-10-21 11:53:43,20000,Home purchase,REJECTED,14.0,0,NaN,NaN,NaN,NaN,Ροδαμάνθη Βαλσαμίδου,290-09-9322,1983-11-06,M,Γρεβενά,37748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2139,41303075,41215957,2017-10-07 21:42:02,50000,Buying a pet,ACCEPTED,6.7,0,NaN,NaN,NaN,NaN,Νεόφυτος Τσιγαρίδας,287-62-7400,1991-02-01,M,Καρδίτσα,2057
96,2174,64760392,51453919,2017-10-21 04:25:59,280000,Buying a pet,ACCEPTED,6.7,0,NaN,NaN,NaN,NaN,Πουλχερία Ανανιάδου,946-51-8824,1977-10-14,M,Καστοριά,33137
97,2190,95726669,47248599,2017-10-30 14:02:05,280000,Refinance existing loans,ACCEPTED,8.7,0,NaN,NaN,NaN,NaN,Ειρήνη-Ροδιά Αλεξοπούλου,793-52-2526,1982-12-12,F,Μεσολόγγι,60814
98,2277,74922937,5863725,2017-10-26 14:31:48,230000,Refinance existing loans,ACCEPTED,7.0,0,NaN,NaN,NaN,NaN,Νταίζη Γκούνη,635-93-3620,1984-01-02,M,Αθήνα,14399
99,2281,95836622,48747986,2017-10-30 14:14:15,270000,Refinance existing loans,REJECTED,8.7,0,NaN,NaN,NaN,NaN,Ελισάβετ Κωστοπούλου,559-86-7347,1970-11-21,M,Ερμούπολη,38047

In [44]:
merged_loans['webvisit_id'] = merged_loans['webvisit_id'].replace(0, np.nan)

In [45]:
del merged_loans['Unnamed: 0_x']
del merged_loans['Unnamed: 0_y']

In [46]:
merged_loans.rename(columns={"timestamp_x" : "timestamp_loan"}, inplace = True)
merged_loans.rename(columns={"timestamp_y" : "timestamp_visit"}, inplace = True)
merged_loans.rename(columns={"id" : "loan_id"}, inplace = True)

In [47]:
# There are loans from 2018 associated with earlier found duplicated user id
merged_loans[merged_loans['user_id'] == 81570228]

,loan_id,user_id,timestamp_loan,loan_amount,loan_purpose,outcome,interest,webvisit_id,timestamp_visit,referrer,campaign_name,name,ssn,birthday,gender,city,zip_code
7579,52607839,81570228,2018-07-02 12:44:22,220000,Buying a pet,ACCEPTED,14.0,25919562.0,2019-03-21 15:41:21,Facebook,display1,Μηνάς Σαμανίδης,016-05-9161,1985-12-17,M,Πρέβεζα,56875
7580,52607839,81570228,2018-07-02 12:44:22,220000,Buying a pet,ACCEPTED,14.0,25919562.0,2019-03-21 15:41:21,Facebook,display1,Ιππόλυτος Παπαδημητριάδης,428-19-7759,1978-10-05,M,Ξάνθη,57332
7659,12867945,81570228,2018-07-04 03:39:23,40000,Refinance existing loans,ACCEPTED,8.7,NaN,NaN,NaN,NaN,Μηνάς Σαμανίδης,016-05-9161,1985-12-17,M,Πρέβεζα,56875
7660,12867945,81570228,2018-07-04 03:39:23,40000,Refinance existing loans,ACCEPTED,8.7,NaN,NaN,NaN,NaN,Ιππόλυτος Παπαδημητριάδης,428-19-7759,1978-10-05,M,Ξάνθη,57332
8294,39476417,81570228,2018-08-03 19:28:23,170000,Home purchase,ACCEPTED,6.7,NaN,NaN,NaN,NaN,Μηνάς Σαμανίδης,016-05-9161,1985-12-17,M,Πρέβεζα,56875
8295,39476417,81570228,2018-08-03 19:28:23,170000,Home purchase,ACCEPTED,6.7,NaN,NaN,NaN,NaN,Ιππόλυτος Παπαδημητριάδης,428-19-7759,1978-10-05,M,Ξάνθη,57332

In [48]:
# Remove loans and data associated with earlier identified bugged user_id
merged_loans.drop(merged_loans[merged_loans['user_id'] == 81570228].index, inplace = True)

In [49]:
merged_loans.head(10)

,loan_id,user_id,timestamp_loan,loan_amount,loan_purpose,outcome,interest,webvisit_id,timestamp_visit,referrer,campaign_name,name,ssn,birthday,gender,city,zip_code
0,9546870,33593540,2017-10-28 03:42:29,80000,Buying a pet,ACCEPTED,8.7,NaN,NaN,NaN,NaN,Δράκων-Δαμιανός Μητρίδης,826-19-7609,1983-05-06,M,Λαμία,37988
1,36469880,41352735,2017-10-24 23:35:34,270000,Refinance existing loans,REJECTED,6.7,72572646.0,2018-09-20 16:49:33,Google,display2,Κομνηνή Βρακά,388-36-2125,1984-10-13,F,Σπάρτη,44532
2,22554526,70055796,2017-10-03 20:59:49,240000,Home purchase,ACCEPTED,7.0,54404642.0,2018-09-23 09:55:30,Twitter,display3,Ελπίς-Λυδία Παυλίδου,506-77-6759,1984-07-14,F,Λιβαδιά,71745
3,27906548,17577009,2017-10-22 08:23:47,190000,Buying a pet,REJECTED,14.0,NaN,NaN,NaN,NaN,Αλκμήνη Ματεντσίδου,053-49-2562,1973-02-25,F,Καβάλα,87994
4,46601919,15988868,2017-10-21 11:53:43,20000,Home purchase,REJECTED,14.0,NaN,NaN,NaN,NaN,Ροδαμάνθη Βαλσαμίδου,290-09-9322,1983-11-06,M,Γρεβενά,37748
5,41957289,46805538,2017-10-17 20:49:22,300000,Refinance existing loans,REJECTED,7.0,NaN,NaN,NaN,NaN,Μελέτιος-Αύγουστος Μηλιώρης,094-52-0699,1990-05-09,M,Λαμία,93320
6,99355109,76460475,2017-10-18 20:52:52,260000,Refinance existing loans,REJECTED,8.7,NaN,NaN,NaN,NaN,Νικηφόρος Δραζιώτης,723-09-3833,1972-03-03,F,Κέρκυρα,5247
7,644608,29541965,2017-10-26 21:47:45,20000,Home purchase,REJECTED,7.0,72004328.0,"2017-12-30 14:52:06,2019-04-28 18:34:06,2018-0...","Google,Twitter,Google,Facebook","display3,display3,display1,display1",Ηλιάνα-Φρύνη Σακελλαρίου,010-50-6442,1973-12-30,M,Άμφισσα,6202
8,36909730,85885340,2017-10-05 05:25:54,190000,Refinance existing loans,REJECTED,14.0,NaN,NaN,NaN,NaN,Φώτιος Κωστάκης,730-03-0522,1996-04-12,M,Καβάλα,89403
9,74013266,78078336,2017-10-22 23:33:03,250000,Home purchase,ACCEPTED,7.0,NaN,NaN,NaN,NaN,Άλκηστις Παπανάνου,371-69-2776,1986-10-07,F,Ιωάννινα,55082

In [50]:
merged_loans.set_index('loan_id')

,user_id,timestamp_loan,loan_amount,loan_purpose,outcome,interest,webvisit_id,timestamp_visit,referrer,campaign_name,name,ssn,birthday,gender,city,zip_code
loan_id,,,,,,,,,,,,,,,,
9546870,33593540,2017-10-28 03:42:29,80000,Buying a pet,ACCEPTED,8.7,NaN,NaN,NaN,NaN,Δράκων-Δαμιανός Μητρίδης,826-19-7609,1983-05-06,M,Λαμία,37988
36469880,41352735,2017-10-24 23:35:34,270000,Refinance existing loans,REJECTED,6.7,72572646.0,2018-09-20 16:49:33,Google,display2,Κομνηνή Βρακά,388-36-2125,1984-10-13,F,Σπάρτη,44532
22554526,70055796,2017-10-03 20:59:49,240000,Home purchase,ACCEPTED,7.0,54404642.0,2018-09-23 09:55:30,Twitter,display3,Ελπίς-Λυδία Παυλίδου,506-77-6759,1984-07-14,F,Λιβαδιά,71745
27906548,17577009,2017-10-22 08:23:47,190000,Buying a pet,REJECTED,14.0,NaN,NaN,NaN,NaN,Αλκμήνη Ματεντσίδου,053-49-2562,1973-02-25,F,Καβάλα,87994
46601919,15988868,2017-10-21 11:53:43,20000,Home purchase,REJECTED,14.0,NaN,NaN,NaN,NaN,Ροδαμάνθη Βαλσαμίδου,290-09-9322,1983-11-06,M,Γρεβενά,37748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28756792,11528512,2019-09-09 15:25:41,30000,Home purchase,ACCEPTED,6.7,NaN,NaN,NaN,NaN,Κλεοπάτρα Μασίκα,094-63-4599,1974-12-09,M,Κέρκυρα,85722
1955435,17298456,2019-09-03 04:21:39,210000,Buying a pet,REJECTED,14.0,NaN,NaN,NaN,NaN,Πωλίνα Πλατάκη,751-66-9382,1989-08-21,M,Φλώρινα,32615
22696084,51463640,2019-09-25 08:20:15,70000,Home purchase,ACCEPTED,14.0,NaN,NaN,NaN,NaN,Στεργιαννώ Τσακίρη,668-65-5303,1990-08-10,F,Καλαμάτα,82565
61735587,48505528,2019-09-21 19:28:37,80000,Buying a pet,ACCEPTED,7.0,NaN,NaN,NaN,NaN,Χριστόφιλη Κοκκίνου,062-16-7137,1978-12-17,F,Λευκάδα,39396
55004298,48505528,2019-09-07 04:22:44,20000,Buying a pet,ACCEPTED,7.0,NaN,NaN,NaN,NaN,Χριστόφιλη Κοκκίνου,062-16-7137,1978-12-17,F,Λευκάδα,39396

In [51]:
merged_loans.to_csv('loan_data.csv', index=False)

In [52]:
# Test to read exported csv file back into dataframe again
df_test = pd.read_csv('loan_data.csv', index_col=0)
df_test.head(20)

,user_id,timestamp_loan,loan_amount,loan_purpose,outcome,interest,webvisit_id,timestamp_visit,referrer,campaign_name,name,ssn,birthday,gender,city,zip_code
loan_id,,,,,,,,,,,,,,,,
9546870,33593540,2017-10-28 03:42:29,80000,Buying a pet,ACCEPTED,8.7,NaN,NaN,NaN,NaN,Δράκων-Δαμιανός Μητρίδης,826-19-7609,1983-05-06,M,Λαμία,37988
36469880,41352735,2017-10-24 23:35:34,270000,Refinance existing loans,REJECTED,6.7,72572646.0,2018-09-20 16:49:33,Google,display2,Κομνηνή Βρακά,388-36-2125,1984-10-13,F,Σπάρτη,44532
22554526,70055796,2017-10-03 20:59:49,240000,Home purchase,ACCEPTED,7.0,54404642.0,2018-09-23 09:55:30,Twitter,display3,Ελπίς-Λυδία Παυλίδου,506-77-6759,1984-07-14,F,Λιβαδιά,71745
27906548,17577009,2017-10-22 08:23:47,190000,Buying a pet,REJECTED,14.0,NaN,NaN,NaN,NaN,Αλκμήνη Ματεντσίδου,053-49-2562,1973-02-25,F,Καβάλα,87994
46601919,15988868,2017-10-21 11:53:43,20000,Home purchase,REJECTED,14.0,NaN,NaN,NaN,NaN,Ροδαμάνθη Βαλσαμίδου,290-09-9322,1983-11-06,M,Γρεβενά,37748
41957289,46805538,2017-10-17 20:49:22,300000,Refinance existing loans,REJECTED,7.0,NaN,NaN,NaN,NaN,Μελέτιος-Αύγουστος Μηλιώρης,094-52-0699,1990-05-09,M,Λαμία,93320
99355109,76460475,2017-10-18 20:52:52,260000,Refinance existing loans,REJECTED,8.7,NaN,NaN,NaN,NaN,Νικηφόρος Δραζιώτης,723-09-3833,1972-03-03,F,Κέρκυρα,5247
644608,29541965,2017-10-26 21:47:45,20000,Home purchase,REJECTED,7.0,72004328.0,"2017-12-30 14:52:06,2019-04-28 18:34:06,2018-0...","Google,Twitter,Google,Facebook","display3,display3,display1,display1",Ηλιάνα-Φρύνη Σακελλαρίου,010-50-6442,1973-12-30,M,Άμφισσα,6202
36909730,85885340,2017-10-05 05:25:54,190000,Refinance existing loans,REJECTED,14.0,NaN,NaN,NaN,NaN,Φώτιος Κωστάκης,730-03-0522,1996-04-12,M,Καβάλα,89403
74013266,78078336,2017-10-22 23:33:03,250000,Home purchase,ACCEPTED,7.0,NaN,NaN,NaN,NaN,Άλκηστις Παπανάνου,371-69-2776,1986-10-07,F,Ιωάννινα,55082
32981943,14991753,2017-10-23 09:17:42,70000,Refinance existing loans,ACCEPTED,7.0,NaN,NaN,NaN,NaN,Βελισσαρία Μητσοπούλου,625-06-6786,1988-05-06,M,Σέρρες,5675
17521143,87956665,2017-10-16 15:40:13,240000,Home purchase,ACCEPTED,7.0,65045146.0,"2019-02-25 03:21:17,2019-07-03 10:02:21,2018-0...","Twitter,Facebook,Google,Google,Google","display3,display2,display1,display1,display2",Μαριλένα Μιχελή,426-14-0045,1970-02-11,M,Τρίκαλα,63144
99597835,64596394,2017-10-21 06:02:10,190000,Refinance existing loans,REJECTED,8.7,33871022.0,NaN,NaN,NaN,Καλλίνικη Σκαφτούρου,553-31-3202,1995-03-16,M,Κοζάνη,9350
91643622,60981988,2017-10-08 11:57:23,100000,Buying a pet,REJECTED,6.7,NaN,NaN,NaN,NaN,Αγνή Συρμού,695-92-7841,1976-05-05,M,Βόλος,75060
92937580,16251586,2017-10-03 05:26:54,170000,Home purchase,REJECTED,8.7,NaN,NaN,NaN,NaN,Αθηνά Γιαννακουδάκη,832-32-2906,1996-08-26,F,Καλαμάτα,30440
5066711,26085422,2017-10-17 22:18:03,80000,Home purchase,REJECTED,7.0,NaN,NaN,NaN,NaN,Ξανθή Πρέκα,052-06-8369,1988-06-03,M,Κατερίνη,62387
42491716,74590388,2017-10-24 16:07:23,30000,Buying a pet,REJECTED,7.0,NaN,NaN,NaN,NaN,Ανδρέας Τσότρας,465-22-4285,1978-04-23,F,Θεσσαλονίκη,165
8704094,93316544,2017-10-25 13:56:14,260000,Home purchase,ACCEPTED,6.7,NaN,NaN,NaN,NaN,Βικτωρία Τζιωρτζή,432-12-4188,1993-12-31,F,Χαλκίδα,90204
84731523,9709421,2017-10-08 02:32:40,240000,Buying a pet,ACCEPTED,6.7,NaN,NaN,NaN,NaN,Βαρσαμία Ζαχαριουδάκη,893-96-3645,1982-04-27,F,Χανιά,39874
1351012,80854090,2017-10-28 11:44:04,20000,Home purchase,ACCEPTED,6.7,NaN,NaN,NaN,NaN,Λάμπρος Ράπτης,111-24-9135,1973-11-04,M,Λιβαδιά,80478